import 'package:flutter/material.dart';

const Color primaryColor = Color(0xFF3369FF);
const Color secondColor = Color(0xFFC6D5FF);
const Color orangeColor = Color(0xFFec9200);
const Color orangeStrongColor = Color(0xFFff7000);
const Color yellowColor = Color(0xFFfdbe3a);
const Color yellowLightColor = Color(0xFFffda47);
const Color bluedarkColor = Color(0xFF000010);
const Color blackLighColor = Color(0xFF191927);
const Color greyLightColor = Color(0xFF4a4a5d);
const Color purpleColor = Color(0xFF5000ff);
const Color navyColor = Color(0xFF162A49);
const Color blackColor = Color(0xFF1f2633);
const Color greyColor = Color(0xFF9f9fb2);
const Color pinkRedColor = Color(0xFFb30075);
const Color redColor = Color(0xFFee0045);
const Color greenColor = Color(0xFF00fdad);
const Color greenAcentColor = Color(0xFF00C9AB);
const Color greenOliveColor = Color(0xFF5efed7);
